
// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/shared/Header";
import Footer from "../components/shared/Footer";
import { GamesProvider } from "../context/GamesContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Friv 2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <GamesProvider>
      <html lang="en">
        <body className={inter.className}>
          <header>
            <Header />
          </header>
          {children}
          <footer>
            <Footer />
          </footer>
        </body>
      </html>
    </GamesProvider>
  );
}
